FROM node:latest AS BUILD_IMAGE

WORKDIR '/dist'

COPY ./package.json .
RUN yarn install --only=production
ARG CACHEBUST=1
RUN yarn upgrade api

COPY ./src ./src
COPY ./public ./public
COPY ./tsconfig.json .
COPY ./.eslintrc.json .

RUN npm run build

EXPOSE 80

FROM nginx
COPY --from=BUILD_IMAGE /dist/build /usr/share/nginx/html
